[build]
builder = "nixpacks"

[[services]]
name = "server"
source = "server"

[services.build]
buildCommand = "npm install"

[services.deploy]
startCommand = "node src/index.js"

[services.health]
Path = "/health"

[[services]]
name = "client"
dockerfile = "yearbook-v2/Dockerfile"

[services.deploy]
startCommand = "npx serve dist/public -l $PORT"
