[build]
builder = "nixpacks"

[[services]]
name = "server"
source = "server"

[services.build]
buildCommand = "npm install"

[services.deploy]
startCommand = "node src/index.js"

[services.health]
Path = "/health"

[[services]]
name = "client"
source = "yearbook-v2"

[services.build]
buildCommand = "pnpm install && pnpm build"

[services.deploy]
startCommand = "npx serve dist/public -l $PORT"
